export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';
export const LIMPIAR_ALERTA_PRODUCTO = 'LIMPIAR_ALERTA_PRODUCTO';


export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO';
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO';
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR';

export const ELIMINAR_ARCHIVO_EXITO = 'ELIMINAR_ARCHIVO_EXITO';
export const ELIMINAR_ARCHIVO_ERROR = 'ELIMINAR_ARCHIVO_ERROR';

export const CREAR_PRODUCTO_EXITO = 'CREAR_PRODUCTO_EXITO';
export const CREAR_PRODUCTO_ERROR = 'CREAR_PRODUCTO_ERROR';
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR';
export const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO';

export const LIMPIAR_STATE_CREACION = 'LIMPIAR_STATE_CREACION';
export const LIMPIAR_STATE = 'LIMPIAR_STATE';

export const OBTENER_PRODUCTO_EXITO = 'OBTENER_PRODUCTO_EXITO';
export const OBTENER_PRODUCTO_ERROR = 'OBTENER_PRODUCTO_ERROR';
export const LISTAR_PRODUCTOS = 'LISTAR_PRODUCTOS';
export const LISTAR_CATEGORIAS = 'LISTAR_CATEGORIAS';









export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_CARRITO = 'TOGGLE_CARRITO';
export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';
export const TOGGLE_BUSCAR = 'TOGGLE_BUSCAR';
export const TOGGLE_TEMA = 'TOGGLE_TEMA';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

